name: Atualizar prog.txt

on:
  schedule:
    - cron: '0 8 * * *'  # Todos os dias às 08:00 UTC
  workflow_dispatch:      # Permite correr manualmente
  push:
    branches:
      - main

jobs:
  atualizar-prog:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Fazer download do ficheiro prog.txt da net
        run: |
          curl -s https://sportsonline.sl/prog.txt -o prog.txt

      - name: Commit e push se houve alterações
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add prog.txt
          git diff --quiet && echo "Sem alterações" || (git commit -m "Atualização diária do prog.txt" && git push)
